name: Security & Dependencies

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  security-audit:
    runs-on: ubuntu-latest
    name: Security Audit
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
      continue-on-error: true
      
    - name: Run dependency check
      uses: actions/dependency-review-action@v4
      if: github.event_name == 'pull_request'

  update-dependencies:
    runs-on: ubuntu-latest
    name: Update Dependencies
    if: github.event_name == 'schedule'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Update dependencies
      run: |
        npm update
        npm audit fix --force || true
        
    - name: Run tests with updated dependencies
      run: |
        npm test
        npm run build
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: '🔄 Automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR updates project dependencies to their latest versions.
          
          ### Changes
          - Updated npm dependencies
          - Applied security fixes where available
          
          ### Testing
          ✅ Unit tests passed
          ✅ Build successful
          
          Please review and merge if all checks pass.
        branch: automated/dependency-updates
        delete-branch: true